### ISSUE TITLE
Installation pulls in an older version of `charmcraft`

### ISSUE THREAD

**Issue by jnsgruk** [charmed-kubernetes/pytest-operator#13]
Was doing some testing with `pytest-operator` and `tox` earlier today and noticed that it pulls in version `0.7.0` of `charmcraft` rather than the latest `1.0.0`.

This is my tox env:

```ini
[testenv:integration]
deps =
    juju
    pytest
    pytest-operator 
    ipdb
commands = pytest -v --tb native --show-capture=no --log-cli-level=INFO -s {posargs:tests/integration}
```

And contents of venv:

```
ls .tox/integration/lib/python3.9/site-packages | grep charmcra
drwxrwxr-x    - jon jon 28 May 15:39 -- charmcraft
drwxrwxr-x    - jon jon 28 May 15:39 -- charmcraft-0.7.0.dist-info
```

Thanks! :)

**Comment by jnsgruk** [comment]
Yeh, I agree, pretty weird!

**Comment by johnsca** [comment]
I confirmed that it tries to use 1.0.0 and below and for some reason will only accept 0.7.0. My best guess is a dependency version conflict between libjuju and charmcraft after 0.7.0, since libjuju has some more restrictive dependency specifications but I'm really not sure and couldn't find the actual conflict.  Regardless, I think it's better to switch to the snap than keep trying to track this down.
